// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCbi01uV3F-9bSwx3nirhI9O2Xi0Ulwec',
    appId: '1:464069298435:web:cbd7569d2281b4751bc136',
    messagingSenderId: '464069298435',
    projectId: 'kisan-dost-abe42',
    authDomain: 'kisan-dost-abe42.firebaseapp.com',
    storageBucket: 'kisan-dost-abe42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb32igsF9ED4eSr8LTM0kIOTinVeh8vUw',
    appId: '1:464069298435:android:884d39fb447f83a51bc136',
    messagingSenderId: '464069298435',
    projectId: 'kisan-dost-abe42',
    storageBucket: 'kisan-dost-abe42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNFJC0foWbGEDZjECE2-CP9apLKu-DNA4',
    appId: '1:464069298435:ios:1b5d6311f09a30521bc136',
    messagingSenderId: '464069298435',
    projectId: 'kisan-dost-abe42',
    storageBucket: 'kisan-dost-abe42.firebasestorage.app',
    iosBundleId: 'com.kisandost.kisanDost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNFJC0foWbGEDZjECE2-CP9apLKu-DNA4',
    appId: '1:464069298435:ios:1b5d6311f09a30521bc136',
    messagingSenderId: '464069298435',
    projectId: 'kisan-dost-abe42',
    storageBucket: 'kisan-dost-abe42.firebasestorage.app',
    iosBundleId: 'com.kisandost.kisanDost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCbi01uV3F-9bSwx3nirhI9O2Xi0Ulwec',
    appId: '1:464069298435:web:d37ab138be3874a21bc136',
    messagingSenderId: '464069298435',
    projectId: 'kisan-dost-abe42',
    authDomain: 'kisan-dost-abe42.firebaseapp.com',
    storageBucket: 'kisan-dost-abe42.firebasestorage.app',
  );

}